CREATE TABLE IF NOT EXISTS `internship_reflection` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `student_id` bigint NOT NULL COMMENT '学生ID',
  `student_name` varchar(100) NOT NULL COMMENT '学生姓名',
  `student_user_id` varchar(50) NOT NULL COMMENT '学号',
  `content` text NOT NULL COMMENT '实习心得内容',
  `submit_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '提交时间',
  `ai_keywords` text COMMENT 'AI提取的关键词（JSON格式）',
  `ai_analysis` text COMMENT 'AI分析结果（JSON格式）',
  `ai_score` decimal(5,2) COMMENT 'AI评分（0-100）',
  `ai_analysis_time` datetime COMMENT 'AI分析时间',
  `status` tinyint DEFAULT '0' COMMENT '状态（0-待分析 1-已分析 2-分析失败）',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` tinyint DEFAULT '0' COMMENT '删除标记（0未删除/1已删除）',
  PRIMARY KEY (`id`),
  KEY `idx_student_id` (`student_id`),
  KEY `idx_student_user_id` (`student_user_id`),
  KEY `idx_submit_time` (`submit_time`),
  KEY `idx_status` (`status`),
  KEY `idx_deleted` (`deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='学生实习心得表';
